# Generated by Django 3.1.3 on 2020-11-09 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClosingPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('open', models.BigIntegerField()),
                ('high', models.BigIntegerField()),
                ('low', models.BigIntegerField()),
                ('close', models.BigIntegerField()),
                ('diff', models.BigIntegerField()),
                ('volume', models.BigIntegerField()),
            ],
        ),
    ]
